version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: mysql+pymysql://imrane:imrane@host.docker.internal:3306/items
    depends_on:
      - db
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: imrane
      MYSQL_DATABASE: items
      MYSQL_USER: imrane
      MYSQL_PASSWORD: imrane
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    environment:
      PMA_HOST: host.docker.internal
      MYSQL_ROOT_PASSWORD: imrane
    ports:
      - "8889:80"
    depends_on:
      - db
  